services:
  caddy:
    build:
      context: .
      dockerfile: CaddyL4.Dockerfile
    container_name: caddy
    restart: unless-stopped
    environment:
      - TZ=Europe/Vilnius
      - CADDY_INGRESS_NETWORKS=proxy
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - /mnt/sata_500/caddy/conf:/etc/caddy
      - /mnt/sata_500/caddy/data:/data/caddy
      - /mnt/sata_500/caddy/temp_conf:/config/caddy
      - /var/run/docker.sock:/var/run/docker.sock:ro
  
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: microchelik
    restart: unless-stopped
    network_mode: host
    environment:
#      - TS_AUTHKEY=
      - TS_EXTRA_ARGS=--accept-dns=true --operator=root
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TZ=Europe/Vilnius
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/sata_500/tailscale:/var/lib/tailscale
      - /run/dbus:/run/dbus
      - /etc/resolv.conf:/etc/resolv.conf
    devices:
      - /dev/net/tun

  pihole:
    container_name: pihole
    labels:
      caddy: "http://pihole.kloud.home, http://pihole.kloud.vpn"
      caddy.reverse_proxy: "127.0.0.1:800"
    image: pihole/pihole:latest
    restart: unless-stopped
    network_mode: host # listens to dns on 530 and http on 800
    environment:
      TZ: 'Europe/Vilnius'
      FTLCONF_webserver_api_password: ${PIHOLE_FTLCONF_webserver_api_password}
      PIHOLE_UID: '1000'
      PIHOLE_GID: '100'
    volumes:
      - /mnt/sata_500/pihole:/etc/pihole
      - /mnt/sata_500/pihole/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      # See https://docs.pi-hole.net/docker/#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE

  postgres:
    build:
      context: .
      dockerfile: Postgres18-atlas.Dockerfile
    container_name: postgres
    restart: unless-stopped
    shm_size: '4gb'
    ports:
      - 5432:5432
    environment:
      - TZ=Europe/Vilnius
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    volumes:
      - /mnt/sata_500/dbs/postgres/data:/var/lib/postgresql      
      - /mnt/sata_500/dbs/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - default
      - backend


  valkey:
    image: valkey/valkey
    container_name: valkey
    restart: unless-stopped
    command: valkey-server --save 240 5 --loglevel warning
    shm_size: '4gb'
    ports:
      - 6379:6379
    environment:
      - TZ=Europe/Vilnius
    volumes:
      - /mnt/sata_500/dbs/valkey:/data
    networks:
      - default
      - backend

  cronicle:
    image: cronicle/edge:latest
    container_name: cronicle
    labels:
      caddy: "http://cron.kloud.home, http://cron.kloud.vpn"
      caddy.reverse_proxy: "{{upstreams 3012}}"
      caddy_ingress_network: "proxy"
    hostname: manager1
    restart: unless-stopped
    command: ["manager"]
    environment:
      - TZ=Europe/Vilnius
      - CRONICLE_manager=1
      - CRONICLE_secret_key=${CRONICLE_SECRET_KEY}
    volumes:
      - /mnt/sata_500/cronicle/data:/opt/cronicle/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/kloud:/home/kloud
      - /mnt/sata_500:/mnt/sata_500
    networks:
      - default
      - proxy

  authelia:
    image: authelia/authelia:4
    user: "1000:100"
    command: ["--config", "/etc/authelia/configuration.yml"]
    labels:
        caddy: "https://${AUTH_DOMAIN}:443"
        caddy.reverse_proxy: "{{upstreams 9091}}"
        caddy_ingress_network: "proxy"
    restart: unless-stopped
    environment:
      X_AUTHELIA_CONFIG_FILTERS: template
      AUTH_DOMAIN: ${AUTH_DOMAIN}
      AUTH_URL: https://${AUTH_DOMAIN}
      ATLAS_PUBLIC_URL: https://atlas.kloud.home.kg
      AUTH_POLICY: ${AUTH_POLICY:-one_factor}
    networks:
      - default
      - proxy
    volumes:
      - /mnt/sata_500/authelia/configuration.yml:/etc/authelia/configuration.yml:ro
      - /mnt/sata_500/authelia/config:/config

networks:
  proxy:
    name: proxy
  backend:
    name: backend
