label: null
backend: Auto
enable: null
clipboard_threshold: null
auto_restart: null
preserve_clipboard: null
toggle_key: RIGHT_ALT
paste_shortcut: null
disable_x11_fast_inject: null
word_separators: null
backspace_limit: null
apply_patch: null
search_trigger: .sss
search_shortcut: ALT+M
undo_backspace: null
show_notifications: null
show_icon: null
secure_input_notification: null
post_form_delay: null
post_search_delay: null
emulate_alt_codes: null
win32_exclude_orphan_events: null
win32_keyboard_layout_cache_interval: null
x11_use_xclip_backend: null
x11_use_xdotool_backend: null
pre_paste_delay: null
restore_clipboard_delay: null
paste_shortcut_event_delay: null
inject_delay: null
key_delay: null
keyboard_layout: null
evdev_modifier_delay: null
includes: null
excludes: null
extra_includes: null
extra_excludes: null
use_standard_includes: null
filter_title: null
filter_class: null
filter_exec: null
filter_os: null
