matches:
- trigger: :div
  replace: <div>$|$</div>
- trigger: :skull3
  replace: 💀💀💀
- trigger: :shrug
  replace: ¯\_(ツ)_/¯
- trigger: ":fliptable:"
  replace: "(╯°□°）╯︵ ┻━┻"
- trigger: ":fixtable:"
  replace: "┬─┬ノ( º _ ºノ)"
- trigger: ":angry-fliptable:"
  replace: "‎(ﾉಥ益ಥ）ﾉ﻿ ┻━┻"
- trigger: :bash-st
  replace: |
    #!/bin/bash
    set -e
    set -o pipefail
- trigger: :bash-fallback
  replace: var="${VARIABLE:-$|$}"
- trigger: :bash-var-unset
  replace: |
    if [ -z ${var+x} ]; then
      echo "var is unset"
      exit 1
    fi
- trigger: :cbore
  replace: "⌴"
- trigger: ":Box:"
  replace: "□"
- trigger: ":cdot:"
  replace: "⋅"
- trigger: ":pm:"
  replace: "±"
- trigger: ":mp:"
  replace: "∓"
