PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;DROP TABLE key_value;
CREATE TABLE key_value (
        key TEXT PRIMARY KEY,
        value TEXT,
        last_modified NUMBER NOT NULL
    );
INSERT INTO key_value VALUES('settings.initialTimestamp','"2024-11-17T18:36:36.249Z"',1731868615);
INSERT INTO key_value VALUES('settings.startOfDay','"04:00"',1731868615);
INSERT INTO key_value VALUES('settings.startOfWeek','"Monday"',1731868615);
INSERT INTO key_value VALUES('settings.durationDefault','14400',1731868615);
INSERT INTO key_value VALUES('settings.landingpage','"/home"',1731868615);
INSERT INTO key_value VALUES('settings.always_active_pattern','""',1731868615);
INSERT INTO key_value VALUES('settings.views','[{"elements":[{"size":3,"type":"top_apps"},{"size":3,"type":"top_titles"},{"size":3,"type":"timeline_barchart"},{"size":3,"type":"top_categories"},{"size":3,"type":"category_tree"},{"size":3,"type":"category_sunburst"},{"props":{"title":"Music","visname":"aw-watcher-media-player"},"type":"custom_vis"}],"id":"summary","name":"Summary"},{"elements":[{"size":3,"type":"top_apps"},{"size":3,"type":"top_titles"}],"id":"window","name":"Window"},{"elements":[{"size":3,"type":"top_domains"},{"size":3,"type":"top_urls"}],"id":"browser","name":"Browser"},{"elements":[{"size":3,"type":"top_editor_files"},{"size":3,"type":"top_editor_projects"},{"size":3,"type":"top_editor_languages"}],"id":"editor","name":"Editor"}]',1731868649);
INSERT INTO key_value VALUES('settings.useMultidevice','true',1732356400);
INSERT INTO key_value VALUES('settings.showYearly','true',1732356407);
INSERT INTO key_value VALUES('settings.requestTimeout','60',1732356415);
INSERT INTO key_value VALUES('settings.theme','"dark"',1732356543);
INSERT INTO key_value VALUES('settings.userSatisfactionPollData','{"isEnabled":false,"nextPollTime":"2024-12-05T18:45:21.685Z","timesPollIsShown":1}',1732819527);
INSERT INTO key_value VALUES('settings.newReleaseCheckData','{"howOftenToCheck":86400,"isEnabled":true,"nextCheckTime":"2024-12-11T20:07:40.024Z","timesChecked":0}',1733861295);
INSERT INTO key_value VALUES('settings.classes','[{"data":{"color":"#0F0","score":10},"id":0,"name":["Work"],"rule":{"regex":"Google Docs|libreoffice|ReText","type":"regex"}},{"data":{},"id":1,"name":["Work","Programming"],"rule":{"regex":"GitHub|Stack Overflow|BitBucket|Gitlab|vim|Spyder|kate|Ghidra|Scite|code|jetbrains-rider","type":"regex"}},{"id":2,"name":["Work","Image"],"rule":{"regex":"GIMP|Inkscape","type":"regex"}},{"id":3,"name":["Work","Video"],"rule":{"regex":"Kdenlive","type":"regex"}},{"data":{},"id":4,"name":["Work","Audio"],"rule":{"ignore_case":true,"regex":"Audacity|org.kde.kid3","type":"regex"}},{"data":{"color":"#68CCCA"},"id":5,"name":["Work","3D"],"rule":{"ignore_case":true,"regex":"Blender|PrusaSlicer","type":"regex"}},{"data":{"color":"#F33"},"id":6,"name":["Media"],"rule":{"type":"none"}},{"data":{"color":"#FDA1FF"},"id":7,"name":["Media","Games"],"rule":{"regex":"Minecraft|RimWorld","type":"regex"}},{"data":{"color":"#F33"},"id":8,"name":["Media","Video"],"rule":{"regex":"YouTube|Plex|VLC","type":"regex"}},{"data":{"color":"#FCC400"},"id":9,"name":["Media","Social Media"],"rule":{"ignore_case":true,"regex":"reddit|Facebook|Twitter|Instagram|devRant","type":"regex"}},{"data":{"color":"#7B64FF"},"id":10,"name":["Media","Music"],"rule":{"ignore_case":true,"regex":"Murglar|Spotify|Deezer|org.strawberrymusicplayer.strawberry|Strawberry Music","type":"regex"}},{"data":{"color":"#9FF"},"id":11,"name":["Comms"],"rule":{"type":"none"}},{"data":{},"id":12,"name":["Comms","IM"],"rule":{"regex":"Messenger|Telegram|Signal|WhatsApp|Rambox|Slack|Riot|Element|Discord|Nheko|NeoChat|Mattermost|org.telegram.desktop","type":"regex"}},{"id":13,"name":["Comms","Email"],"rule":{"regex":"Gmail|Thunderbird|mutt|alpine","type":"regex"}},{"data":{"color":"#CCC"},"id":14,"name":["Uncategorized"],"rule":{"type":"none"}},{"data":{"color":"#DBDF00"},"id":15,"name":["Work","Programming","Paymentsng"],"rule":{"ignore_case":true,"regex":"paymentsng","type":"regex"}},{"data":{"color":"#AEA1FF"},"id":16,"name":["General desktop stuff"],"rule":{"ignore_case":false,"regex":"Dolphin|org.kde.dolphin|plasmashell|kwin_wayland|Settings","type":"regex"}},{"data":{"color":"#FB9E00"},"id":17,"name":["General desktop stuff","Terminal"],"rule":{"ignore_case":true,"regex":"konsole|yakuake","type":"regex"}},{"data":{"color":"#73D8FF"},"id":18,"name":["General desktop stuff","Browsing"],"rule":{"regex":"firefox|google-chrome|Mozilla Firefox","type":"regex"}},{"data":{"color":"#6c9f9f"},"id":19,"name":["Comms","IM","Аня"],"rule":{"regex":"Аня","type":"regex"}},{"data":{"color":"#A4DD00"},"id":20,"name":["Work","Programming","DB"],"rule":{"regex":"DBeaver","type":"regex"}},{"data":{"color":"#68BC00"},"id":21,"name":["Work","Programming","Api"],"rule":{"ignore_case":true,"regex":"postman","type":"regex"}}]',1741465114);
COMMIT;
