services:
  app:
    image: supahgreg/tt-rss:latest
    container_name: tt-rss-app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /mnt/sata_500/rss/tt-rss/app:/var/www/html
      - /mnt/sata_500/rss/tt-rss/config.d:/opt/tt-rss/config.d:ro

  updater:
    image: supahgreg/tt-rss:latest
    container_name: tt-rss-updater
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /mnt/sata_500/rss/tt-rss/app:/var/www/html
      - /mnt/sata_500/rss/tt-rss/config.d:/opt/tt-rss/config.d:ro
    depends_on:
      - app
    command: /opt/tt-rss/updater.sh


  web-nginx:
    image: supahgreg/tt-rss-web-nginx:latest
    container_name: tt-rss-nginx
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - /mnt/sata_500/rss/tt-rss/app:/var/www/html:ro
    depends_on:
      - app

  rsshub:
    image: diygod/rsshub:chromium-bundled
    container_name: rsshub
    restart: unless-stopped
    ports:
      - '1200:80'
    environment:
      - NODE_ENV=production
      - CACHE_TYPE=redis
      - REDIS_URL=redis://172.17.0.1:6379/
      - PORT=80
      - CACHE_EXPIRE=3600          # 1 Hour
      - CACHE_CONTENT_EXPIRE=18000 # 5 hours
      # - TWITTER_USERNAME=gduwer76840
      # - TWITTER_PASSWORD=ktI5HeTtNEHLzrm43JjtN9CGb7mfg1
      # - TWITTER_PHONE_OR_EMAIL=x.cheek958@aleeas.com
      - TWITTER_AUTH_TOKEN=${RSSHUB_TWITTER_AUTH_TOKEN}
      
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1:80/healthz']
      interval: 30s
      timeout: 10s
      retries: 3
