services:
  code-server:
    # image: lscr.io/linuxserver/code-server:latest
    build: .
    container_name: code-server
    labels:
      caddy: "https://code.kloud.home.kg"
      caddy.reverse_proxy: "{{upstreams 8443}}"
      caddy_ingress_network: "proxy"
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Vilnius
      - DEFAULT_WORKSPACE=/config/workspace
      - PASSWORD=${CODE_SERVER_PASSWORD}
      - SUDO_PASSWORD=${CODE_SERVER_SUDO_PASSWORD}
      - PWA_APPNAME=code-server
    volumes:
      - /mnt/sata_500/code-server:/config
    tmpfs:
      - /config/.local/share/code-server/coder-logs:uid=1000,gid=100,mode=0755
      - /config/data/logs:uid=1000,gid=100,mode=0755

networks:
  proxy:
    external: true
    name: proxy
