#!/usr/bin/env chezmoi_modify_manager

source auto

# Add your ignores and transforms here
#ignore section "my-section"
#ignore "exact section name without brackets" "exact key name"
#ignore regex "section.*" "key_prefix_.*"
#transform "section" "key" transform_name read="the docs" for="more detail on transforms"

ignore section "webAppClientService"
ignore section "ownCloudInfo"
ignore section "layout-initial"
ignore section "ai"
ignore regex ".*Dialog" ".*"
ignore regex ".*Folder-\\d*" ".*"
ignore "MainWindow" "geometry"
ignore "MainWindow" "menuBarGeometry"
ignore "General" "versionSplitterSizes"
ignore "General" "ActiveNoteHistoryItem"
ignore "General" "LastUpdateCheck"
ignore "General" "PiwikClientId"
ignore "General" "cryptoKey"
ignore "General" "recentNoteFolders"
ignore regex "General" "NoteHistory-\\d*"
ignore "webSocketServerService" "bookmarkSuggestionApiToken"
ignore "webSocketServerService" "token"
