[aw-qt]
autostart_modules = ["aw-server-rust", "aw-watcher-afk", "aw-awatcher", "aw-watcher-media-player", "aw-sync"]
# "aw-watcher-lastfm", "aw-importer-lastfm", "aw-watcher-netstatus",

[aw-qt-testing]
#autostart_modules = ["aw-server", "aw-watcher-afk", "aw-watcher-window"]
