[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "opt-level=2", "-C", "target-cpu=native", "-C", "link-arg=--ld-path=mold"]

# Faster compilations when doing cargo run
# https://davidlattimore.github.io/working-on-rust-iteration-time.html
[profile.dev]
# opt-level = 1          # Use slightly better optimizations.
debug = 0                # Skip compiling the debug information
strip = "debuginfo"      # Skip linking the debug information

