name: utilities
services:
    
    bentopdf:
        image: ghcr.io/alam00000/bentopdf-simple:latest
        container_name: bentopdf
        labels:
          caddy: "http://pdf.kloud.home, http://pdf.kloud.vpn"
          caddy.reverse_proxy: "{{upstreams 8080}}"
          caddy_ingress_network: "proxy"
        restart: unless-stopped
        networks:
          - default
          - proxy

    homepage:
        image: ghcr.io/gethomepage/homepage:latest
        container_name: homepage
        labels:
          caddy: "http://kloud.home, http://kloud.vpn"
          caddy.reverse_proxy: "{{upstreams 3000}}"
          caddy_ingress_network: "proxy"
        restart: unless-stopped
        user: 1000:100
        environment:
            - TZ=Europe/Vilnius
            - HOMEPAGE_ALLOWED_HOSTS=kloud.home,kloud.vpn,192.168.50.180:3333,100.108.149.90:3333,microcehlik.local:3333
            - PUID=1000
            - PGID=100
        volumes:
            - /mnt/sata_500/homepage:/app/config
            - /var/run/docker.sock:/var/run/docker.sock:ro
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - default
            - base
            - booklore
            - kitchenowl
            - linkwarden
            - media
            - monitoring
            - neko
            - rss
            - proxy

    languagetool:
        image: erikvl87/languagetool:latest
        container_name: languagetool
        labels:
          caddy: "https://sceakbiryzigvgdfrjbumjvivedwzchd.kloud.home.kg"
          caddy.reverse_proxy: "{{upstreams 8010}}"
          caddy_ingress_network: "proxy"
        restart: unless-stopped
        user: 1000:100
        environment:
            - TZ=Europe/Vilnius
            - Java_Xms=512m
            - Java_Xmx=2g
            - langTool_abTest=
            - langTool_abTestClients=
            - langtool_pipelinePrewarming=true
            - langtool_languageModel=/ngrams
        volumes:
            - /mnt/sata_500/languagetool/ngrams:/ngrams:ro
            - /mnt/sata_500/languagetool/logback.xml:/LanguageTool/logback.xml
        networks:
          - default
          - proxy


    ntfy:
        image: binwiederhier/ntfy
        container_name: ntfy
        labels:
          caddy: "https://ntfy.kloud.home.kg"
          caddy.reverse_proxy: "{{upstreams 81}}"
          caddy_ingress_network: "proxy"
        command: serve
        restart: unless-stopped
        environment:
            - TZ=Europe/Vilnius
        user: 1000:100
        volumes:
            - /mnt/sata_500/ntfy/cache:/var/cache/ntfy
            - /mnt/sata_500/ntfy/config:/etc/ntfy
        networks:
          - default
          - proxy

    mailrise:
        image: yoryan/mailrise:latest
        container_name: mailrise
        restart: unless-stopped
        volumes:
            - /mnt/sata_500/mailrise/mailrise.conf:/etc/mailrise.conf:ro
        environment:
            - PUID=1000
            - PGID=100
        ports:
            - 8025:8025

    syncthing:
        image: syncthing/syncthing:latest
        container_name: syncthing
        labels:
          caddy: "http://sync.kloud.home, http://sync.kloud.vpn"
          caddy.reverse_proxy: "127.0.0.1:8384"
        restart: unless-stopped
        hostname: microchelik
        environment:
            - PUID=1000
            - PGID=100
            - PCAP=cap_chown,cap_fowner+ep
            - STGUIADDRESS=
            - UMASK=027 # https://wintelguy.com/umask-calc.pl
            - TZ=Europe/Vilnius
        network_mode: host # 22000, 22001, 22027, 8384
        volumes:
            - /mnt/sata_500/syncthing:/var/syncthing
            - /mnt/sata_500/syncthing/config:/var/syncthing/config
        healthcheck:
            test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
            interval: 5m
            timeout: 10s
            retries: 3

    syncthing-relay:
        image: syncthing/relaysrv
        container_name: syncthing-relay
        hostname: microchelik-relay
        environment:
          - PUID=1000
          - PGID=100
        network_mode: host # 22067, 22070 for stats
        restart: unless-stopped
        entrypoint: ["/bin/entrypoint.sh", "/bin/strelaysrv", "-pools", "", "-provided-by=", "kloud's homelab"]
        volumes:
          - /mnt/sata_500/syncthing/relay:/var/strelaysrv

    voux:
        image: ghcr.io/quintixlabs/voux/voux:latest
        container_name: voux
        labels:
          caddy: "https://voux.kloud.home.kg"
          caddy.reverse_proxy: "{{upstreams 8787}}"
          caddy_ingress_network: "proxy"
        restart: unless-stopped
        user: 1000:100
        environment:
            - ADMIN_USERNAME=admin
            - ADMIN_PASSWORD=${VOUX_ADMIN_PASSWORD}
        volumes:
            - /mnt/sata_500/voux:/app/data
        networks:
          - default
          - proxy


    spoolman:
      image: ghcr.io/donkie/spoolman:latest
      container_name: spoolman
      labels:
        caddy: "http://spoolman.kloud.home, http://spoolman.kloud.vpn"
        caddy.reverse_proxy: "{{upstreams 8000}}"
        caddy_ingress_network: "proxy"
      restart: unless-stopped
      volumes:
        - type: bind
          source: /mnt/sata_500/spoolman
          target: /home/app/.local/share/spoolman
      environment:
        - TZ=Europe/Vilnius
        - PUID=1000
        - PGID=100
      networks:
        - default
        - proxy

    atuin:
        image: ghcr.io/atuinsh/atuin:18.13.5
        container_name: atuin
        labels:
          caddy: "https://atuin.kloud.home.kg"
          caddy.reverse_proxy: "{{upstreams 8888}}"
          caddy_ingress_network: "proxy"
        restart: unless-stopped
        networks:
            - default
            - backend
            - proxy
        command: start
        user: 1000:100
        volumes:
          - "/mnt/sata_500/atuin:/config"
        environment:
          ATUIN_HOST: "0.0.0.0"
          ATUIN_OPEN_REGISTRATION: "true"
          ATUIN_DB_URI: ${ATUIN_DB_URI}
          RUST_LOG: info

    plik:
        image: rootgg/plik:latest
        container_name: plik
        labels:
          caddy: "https://plik.kloud.home.kg"
          caddy.reverse_proxy: "{{upstreams 8080}}"
          caddy_ingress_network: "proxy"
        restart: "unless-stopped"
        user: 1000:100
        volumes:
          - /mnt/sata_500/plik/plikd.cfg:/home/plik/server/plikd.cfg
          - /mnt/sata_500/plik/data:/data
        networks:
          - default
          - proxy
   

networks:
  proxy:
    external: true
    name: proxy
  backend:
    external: true
    name: backend
  base:
    external: true
    name: base_default
  booklore:
    external: true
    name: booklore_default
  kitchenowl:
    external: true
    name: kitchenowl_default
  linkwarden:
    external: true
    name: linkwarden_default
  media:
    external: true
    name: media_default
  monitoring:
    external: true
    name: monitoring_default
  neko:
    external: true
    name: neko_default
  rss:
    external: true
    name: rss_default
